language: cpp
matrix:
  include:
    - os: linux
      dist: xenial
      sudo: false
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7  && CXX=g++-7"
      before_install:
        - eval "${MATRIX_EVAL}"

    - os: linux
      dist: xenial
      sudo: false
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-trusty-6.0
          packages:
          - clang-6.0
          - libstdc++-7-dev
      env:
        - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0"
      before_install:
        - eval "${MATRIX_EVAL}"

script:
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .
  - make test
